export const products = [
    {
        id: 0,
        name: "Wood Old Style",
        category: "Chair",
        price: 52,
        imageUrl: "chair-1.jpg",
        rating: 4,
    },
    {
        id: 1,
        name: "Stylies Chair",
        category: "Chair",
        price: 48,
        imageUrl: "chair-2.jpg",
        rating: 5,
    },
    {
        id: 2,
        name: "Royal Chair",
        category: "Chair",
        price: 69,
        imageUrl: "chair-3.jpg",
        rating: 5,
    },
    {
        id: 3,
        name: "Golder Chair",
        category: "Chair",
        price: 42,
        imageUrl: "chair-4.jpg",
        rating: 4,
    },
    {
        id: 4,
        name: "Golden Red Chair",
        category: "Chair",
        price: 75,
        imageUrl: "chair-5.jpg",
        rating: 5,
    },
    {
        id: 5,
        name: "Choclate Beds",
        category: "Beds",
        price: 152,
        imageUrl: "beds-1.jpg",
        rating: 5,
    },
    {
        id: 6,
        name: "platform Beds",
        category: "Beds",
        price: 141,
        imageUrl: "beds-2.jpg",
        rating: 4,
    },
    {
        id: 7,
        name: "Dark White Beds",
        category: "Beds",
        price: 165,
        imageUrl: "beds-3.jpg",
        rating: 5,
    },
    {
        id: 8,
        name: "Golden Beds",
        category: "Beds",
        price: 130,
        imageUrl: "beds-4.jpg",
        rating: 4,
    },
    {
        id: 9,
        name: "fom Platform Beds",
        category: "Beds",
        price: 155,
        imageUrl: "beds-5.jpg",
        rating: 5,
    },
    {
        id: 10,
        name: "Non Style Chair",
        category: "Sofa",
        price: 80,
        imageUrl: "sofa-1.jpg",
        rating: 4,
    },
    {
        id: 11,
        name: "luxaries Sofa",
        category: "Sofa",
        price: 99,
        imageUrl: "sofa-2.jpg",
        rating: 5,
    },
    {
        id: 12,
        name: "Flat Sofa",
        category: "Sofa",
        price: 90,
        imageUrl: "sofa-3.png",
        rating: 5,
    },
    {
        id: 13,
        name: "Red Sofa",
        category: "Sofa",
        price: 95,
        imageUrl: "sofa-4.png",
        rating: 4,
    },
    {
        id: 14,
        name: "Stylies Sofa",
        category: "Sofa",
        price: 88,
        imageUrl: "sofa-5.jpg",
        rating: 4,
    },
    {
        id: 15,
        name: "Table Lamp",
        category: "Lamp",
        price: 40,
        imageUrl: "lamp-1.jpg",
        rating: 5,
    },
    {
        id: 16,
        name: "Daining Lamp",
        category: "Lamp",
        price: 32,
        imageUrl: "lamp-2.jpg",
        rating: 4,
    },
    {
        id: 17,
        name: "Style Lamp",
        category: "Lamp",
        price: 35,
        imageUrl: "lamp-3.jpg",
        rating: 5,
    },
    {
        id: 18,
        name: "Read Lamp",
        category: "Lamp",
        price: 42,
        imageUrl: "lamp-4.jpg",
        rating: 5,
    },
    {
        id: 19,
        name: "Side Lamp",
        category: "Lamp",
        price: 45,
        imageUrl: "lamp-5.jpg",
        rating: 5,
    },
];